#!/bin/bash

trials=100
mkdir experiments/experiment6.${1}.${2}.$3

for num in $(seq 1 $trials); do
    echo "running trial" $num;
    java main/Shell struct=$1 weight=$2 dummyroot=$3 filename=experiments/experiment6.${1}.${2}.${3}/experiment6.${1}.${2}.${3}.trial$num
done

